version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "posystem"
      POSTGRES_USER: "aman"
      POSTGRES_PASSWORD: "admin"
      TZ: "Europe/London"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "amanwork@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80 
    depends_on:
      - postgres

volumes:
  postgres-data:

